# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/gaspare',
                'doc_host': 'https://mikonapoli.github.io',
                'git_url': 'https://github.com/mikonapoli/gaspare',
                'lib_path': 'gaspare'},
  'syms': {'gaspare.core': {'gaspare.core.foo': ('core.html#foo', 'gaspare/core.py')}}}
